# Generated by Django 5.2 on 2025-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('job_urls', models.TextField()),
                ('ignore_companies', models.TextField()),
                ('jobs_per_company', models.IntegerField()),
            ],
        ),
    ]
