# Generated by Django 5.2 on 2025-04-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FromData',
            new_name='FormData',
        ),
    ]
