# Generated by Django 5.2 on 2025-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indeed', '0002_rename_fromdata_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='max_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='ignore_companies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='jobs_per_company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
